### ISSUE TITLE
Pasting multi-line Markdown into input doesn't work correctly

### ISSUE THREAD

**Issue by michaelrhanson** [fbreuer/qute-html5#21]
I'm finding that when I paste some Markdown into Qute, it isn't parsed properly.  

The presence of newlines in the paste buffer appears to confuse the Markdown processor - if I paste a line that doesn't contain newlines it works fine, but if I paste a longer chunk, the text appears but when I double-click it disappears.

Platform: MacOS 10.6, version July 1, 2011

**Comment by fbreuer** [comment]
Hi Mike!

Thanks for reporting this issue. I am trying to reproduce it, but have
failed so far. I tried copying multiparagraph Markdown text from TextEdit in
MacOS 10.6.7 into Qute. After the double-click, the markup was split
correctly into several paragraphs and none of it was lost.

Could you provide a test case? Also, what application are you copying from?
This might make a difference.

Thanks,
Felix

2011/7/1 michaelrhanson <
reply@reply.github.com>

> I'm finding that when I paste some Markdown into Qute, it isn't parsed
> properly.
> 
> The presence of newlines in the paste buffer appears to confuse the
> Markdown processor - if I paste a line that doesn't contain newlines it
> works fine, but if I paste a longer chunk, the text appears but when I
> double-click it disappears.
> 
> Platform: MacOS 10.6, version July 1, 2011
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fbreuer/qute-html5/issues/21

## 

http://www.felixbreuer.net

**Comment by fbreuer** [comment]
I have now been able to reproduce the issue. It occurs when rich text (with HTML tags) is pasted into Qute's edit view. This happens, for example, when copying (formatted) text from web browsers or office suites into Qute.

I will have to solve this by using Chromeless' clipboard module.

For the time being, a workaround is to copy markup from text editors.

**Comment by fbreuer** [comment]
I have pushed a patch fixing this issue.

@Mike: It would be great if you could test whether this works now. Either pull the code from github and try to get it to compile, or wait for the next release (in a week or so). Thanks!

**Comment by michaelrhanson** [comment]
I am still seeing the problem in version 0.2.

Method to reproduce (on Mac OS 10.6.7):
- navigate to a github page containing a .MD file
- click "raw"
- select all, copy
- create new document in Qute
- paste
- click to submit MD source - paragraph disappears and x-offset is incorrect

Pasting the text of the MD into a text buffer and copying it back out solves the problem, as indicated.

**Comment by fbreuer** [comment]
Hi Michael,

thanks for testing!

I can reproduce this problem with Firefox on Mac OS. However, everything
works fine with Firefox on Windows or Safari on Mac OS. Strange. Could you
check whether copy and paste works with Safari on your system?

I will have to investigate further.

Felix

2011/7/12 michaelrhanson <
reply@reply.github.com>

> I am still seeing the problem in version 0.2.
> 
> Method to reproduce (on Mac OS 10.6.7):
> - navigate to a github page containing a .MD file
> - click "raw"
> - select all, copy
> - create new document in Qute
> - paste
> - click to submit MD source - paragraph disappears and x-offset is
>   incorrect
> 
> Pasting the text of the MD into a text buffer and copying it back out
> solves the problem, as indicated.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fbreuer/qute-html5/issues/21#issuecomment-1550551

## 

http://www.felixbreuer.net

**Comment by fbreuer** [comment]
Ah, I found the source of the confusion.

Pasting with cmd+v causes trouble (because this triggers Chromeless' default pasting mechanism). Pasting with ctrl+v however works, as this uses the new code. Of course, this confusion should be avoided in the future.

Bottom line: Use ctrl+v to paste on Mac OS. Until I get the keybindings sorted out.
