### ISSUE TITLE
preview issues

### ISSUE THREAD

**Issue by pkra** [fbreuer/qute-html5#32]
using linux binaries on ubuntu 11.04

Apologies for the vagueness -- I haven't found a way to reproduce this effectively.

This is all in single column mode
- Sometimes, when I edit a paragraph and switch to a different paragraph with the mouse, the first one does not switch back to preview. Switching back and forth with the keyboard corrects this.
- Sometimes, qute leaves editing mode after a few seconds of inactivity. That's actually nice (if intended), but typing does not get you back into editing mode. ctrl+up/down does get you into the surrounding paragraphs -- but that's not very optimal when editing a longer paragraph...
- Sometimes, changes do not show up in preview. Switching to two column view and back seems to correct this.

**Comment by fbreuer** [comment]
> Sometimes, when I edit a paragraph and switch to a different paragraph with the mouse, the first one does not switch back to preview. Switching back and forth with the keyboard corrects this.

Yes. When paragraph A is in edit mode and you click on paragraph B once, then both A and B are in edit mode. This is the intended behavior right now. Would you prefer if Qute enforced that only one paragraph (at most) can be in edit mode at a time?

> Sometimes, qute leaves editing mode after a few seconds of inactivity. That's actually nice (if intended), but typing does not get you back into editing mode. ctrl+up/down does get you into the surrounding paragraphs -- but that's not very optimal when editing a longer paragraph...

Hm, I have not encountered this before. In any case, it is not intended behavior. I will have to investigate that.

> Sometimes, changes do not show up in preview. Switching to two column view and back seems to correct this.

This definitely should not happen. It would be great if we found a way to reproduce this bug.

**Comment by pkra** [comment]
Ah, ok! I don't mind intended behaviour ;)

I'll try to reproduce the other two.

**Comment by fbreuer** [comment]
> Sometimes, qute leaves editing mode after a few seconds of inactivity. That's actually nice (if intended), but typing does not get you back into editing mode. ctrl+up/down does get you into the surrounding paragraphs -- but that's not very optimal when editing a longer paragraph...

I was able to reproduce this. It had to do with event handlers not being properly unbound when exiting two column mode. Should be fixed now.

**Comment by pkra** [comment]
Yep, looks fixed in 0.3beta

**Comment by pkra** [comment]
the third issue from my original issue is still there:

under ubuntu 11.04 the linux binary in single column mode consistently does not switch to preview (if I do ctrl+t to leave and get back into editing mode it does generate a preview).

Example:

When writing a new paragraph, moving back to a previous paragraph with ctrl+up fails to produce a preview for the newly typed paragraph, i.e., the new paragraph is displayed empty/invisible even if something was written in the new paragraph. Going back and forth between the two or more paragraphs does not help.

(sorry for the complicated description :(  I hope the example helps you reproduce it...)

**Comment by fbreuer** [comment]
thanks for the example! i got what you mean.

this should be fixed in the current git source.

2011/8/3 pkra <
reply@reply.github.com>

> the third issue from my original issue is still there:
> 
> under ubuntu 11.04 the linux binary in single column mode consistently does
> not switch to preview (if I do ctrl+t to leave and get back into editing
> mode it does generate a preview).
> 
> Example:
> 
> When writing a new paragraph, moving back to a previous paragraph with
> ctrl+up fails to produce a preview for the newly typed paragraph, i.e., the
> new paragraph is displayed empty/invisible even if something was written in
> the new paragraph. Going back and forth between the two or more paragraphs
> does not help.
> 
> (sorry for the complicated description :(  I hope the example helps you
> reproduce it...)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fbreuer/qute-html5/issues/32#issuecomment-1714889

## 

http://www.felixbreuer.net
